#!/bin/bash

git diff --cached --name-only | while read FILE; do
if [[ "$FILE" =~ ^.+(php|inc|module|install|test)$ ]]; then
    RESULT=$(grep "dpm(" "$FILE")
    if [ ! -z $RESULT ]; then
      exec < /dev/tty
      printf "Your commit contains a call to dpm. Do you want to continue? [Yy/nN]"
      read REPLY
      if [[ ! $REPLY =~ ^[Yy]$ ]]
        then
	echo "Commit aborted"
        exit 1
      else
        exit 0
      fi
    fi
fi
done
